// music.mjs — the background music: none, a file you supply, or a track generated by ElevenLabs.
// Plain English: generation happens ONLY when you run `video-loop music generate`, from the music
// brief agreed in project.toml. The track is saved with its request details and fingerprint and
// reused for every preview, revision and the final master — changing captions or the music volume
// never buys another track. If the edit grows longer than the track, the tool says so and offers
// choices; it never silently loops or cuts the film to fit. A supplied file never leaves the computer.

import { existsSync } from "node:fs";
import { join } from "node:path";
import { requireKey, request, beginPaid, endPaid } from "./elevenlabs.mjs";
import { probeMedia, audioDurationMs } from "./probe.mjs";
import { sha256, sha256File, stableJson, writeJson, writeAtomic, readJsonOpt, ensureDir, Failure, Pending, log } from "./util.mjs";

export const MUSIC_MIN_MS = 3000, MUSIC_MAX_MS = 600000;
const TAIL_MS = 1500;   // generate a little longer than the film so the fade-out lands inside the music

export function musicRequest(cfg, filmMs) {
  return { prompt: cfg.music.prompt.trim(), music_length_ms: Math.ceil((filmMs + TAIL_MS) / 1000) * 1000, model_id: cfg.music.model, force_instrumental: cfg.music.instrumental };
}

/** `video-loop music generate` — one deliberate, paid generation sized to the current edit. */
export async function generateMusic(ctx, { filmMs, retry = false, regenerate = false, envFile }) {
  const { cfg, paths, sp } = ctx;
  if (cfg.music.source !== "elevenlabs") throw new Failure(`music.source is "${cfg.music.source}" — set music.source = "elevenlabs" and music.prompt to generate a track`);
  if (!filmMs) throw new Pending("the edit's length is not known yet — run board first so the track can be sized to the film", ["video-loop board <project>"]);
  const body = musicRequest(cfg, filmMs);
  if (body.music_length_ms < MUSIC_MIN_MS || body.music_length_ms > MUSIC_MAX_MS)
    throw new Failure(`ElevenLabs music can be ${MUSIC_MIN_MS / 1000}–${MUSIC_MAX_MS / 1000}s long in prompt mode; this film needs ${body.music_length_ms / 1000}s`,
      ["supply your own track: music.source = \"file\"", "or prepare a longer arrangement yourself; the film is never cut to fit the music"]);
  // --regenerate gets its own cache entry, so earlier revisions keep the exact track they used
  const key16 = sha256(stableJson(body) + (regenerate ? `|regen ${Date.now()}` : "")).slice(0, 16), dir = ensureDir(sp.musicCache);
  const file = join(dir, `${key16}.mp3`), meta = join(dir, `${key16}.json`);
  if (existsSync(file) && existsSync(meta) && !regenerate) {
    const m = readJsonOpt(meta); writeJson(sp.music, { ...m, selected_at: new Date().toISOString() });
    log(`MUSIC: this exact brief and length was generated before — reusing it (no new request)`); return m;
  }
  const apiKey = requireKey({ projectDir: paths.project, envFile }, "music generation");
  const marker = join(dir, `${key16}.pending.json`);
  beginPaid(marker, { what: "music generation", request: body }, { retry });
  log(`MUSIC: generating ${body.music_length_ms / 1000}s of ${body.force_instrumental ? "instrumental " : ""}music with ElevenLabs (${body.model_id}) from the brief: "${body.prompt.slice(0, 90)}"…`);
  let res;
  try { res = await request({ key: apiKey, path: "/v1/music", json: body, query: { output_format: "mp3_44100_192" }, what: "music generation", timeoutMs: 300000 }); }
  catch (e) { if (!e.ambiguous) endPaid(marker); throw e; }
  endPaid(marker);
  const ct = res.contentType.split(";")[0];
  if (!res.bytes.length || /json|text|html/.test(ct)) throw new Failure(`music generation: ElevenLabs replied with ${ct || "nothing"}, not audio${res.bytes.length ? ` (${res.bytes.toString("utf8").slice(0, 160)})` : ""}`);
  const tmp = `${file}.part`; writeAtomic(tmp, res.bytes);
  const pm = probeMedia(tmp);
  if (!pm.has_audio || !(pm.audio.duration_s > 1)) throw new Failure("music generation: the reply is not playable audio");
  writeAtomic(file, res.bytes);
  const rec = { source: "elevenlabs", file, sha256: await sha256File(file), duration_ms: audioDurationMs(file), request: body,
    provider: "elevenlabs", endpoint: "/v1/music", output_format: "mp3_44100_192", ids: res.ids, created_at: new Date().toISOString() };
  writeJson(meta, rec); writeJson(sp.music, { ...rec, selected_at: rec.created_at });
  log(`MUSIC OK: ${(rec.duration_ms / 1000).toFixed(1)}s track saved (${Object.entries(res.ids).map(([k, v]) => `${k} ${v}`).join(", ") || "no id header"})`);
  return rec;
}

/**
 * The music asset for a render, without ever generating. Returns null for "none".
 * Checks the track is long enough for the film (or that looping was chosen explicitly).
 */
export async function musicForRender(ctx, filmMs) {
  const { cfg, paths, sp } = ctx; const src = cfg.music.source;
  if (src === "none") return null;
  let rec;
  if (src === "file") {
    if (!existsSync(paths.musicFile)) throw new Failure(`music file not found: ${cfg.music.file}`);
    const pm = probeMedia(paths.musicFile);
    if (!pm.has_audio) throw new Failure(`music file ${cfg.music.file} has no audio`);
    rec = { source: "file", file: paths.musicFile, sha256: await sha256File(paths.musicFile), duration_ms: audioDurationMs(paths.musicFile) };
  } else {
    rec = readJsonOpt(sp.music);
    const want = musicRequest(cfg, rec?.request?.music_length_ms ? rec.request.music_length_ms - TAIL_MS : filmMs);
    if (!rec || rec.source !== "elevenlabs" || !existsSync(rec.file) || rec.request.prompt !== want.prompt || rec.request.model_id !== want.model_id || rec.request.force_instrumental !== want.force_instrumental)
      throw new Pending("the music brief has no generated track yet (generation is a deliberate, paid step)", ["video-loop music generate <project>"]);
  }
  if (rec.duration_ms < filmMs && !cfg.music.loop)
    throw new Pending(`the music is ${(rec.duration_ms / 1000).toFixed(1)}s but the film is ${(filmMs / 1000).toFixed(1)}s`, [
      src === "elevenlabs" ? "generate a longer track: video-loop music generate <project> --regenerate" : "choose a longer music.file",
      "or set music.loop = true to repeat the track deliberately"]);
  return rec;
}
